/*
날짜 : 2025.07.23
이름 : 서현우
내용 : sql연습문제4

*/

--실습 1
 ALTER SESSION Set "_ORACLE_SCRIPT"=true;
CREATE USER library IDENTIFIED BY 1234;
GRANT CONNECT, RESOURCE, UNLIMITED TABLESPACE TO library;

--실습2
create table Member(
    member_Id Number(4) not null primary key,
    name varchar(40) not null,
    address varchar(100) default null,
    hp char(13) default null unique,
    join_date date not null
);


create table Book(
    book_Id number(5) not null primary key,
    title varchar(50) not null,
    author varchar(40) not null,
    publisher varchar(40) not null,
    available char(1) default null,
    reg_date date not null
);
drop table book;

create table loan(
    loan_Id number generated by default as identity primary key,
    member_Id number(4) not null,
    book_Id number(5) not null,
    loan_date date default null,
    return_date date default null,
    actual_date date default null,
    FOREIGN key (member_Id) REFERENCES member (member_id),
    FOREIGN key (book_id) REFERENCES book (book_id)    
);
drop table loan;
--3
insert into member values(1001, '김유신', '서울특별시 강남구 역삼동', '010-1234-1001', '2024-01-10 09:15:00');
insert into member values(1002, '김춘추', '대전광역시 유성구 장대동', '010-1234-1002', '2024-02-14 14:30:45');
insert into member values(1003, '장보고', '대구광역시 수성구 반월동', '010-1234-1003', '2024-03-01 11:05:20');
insert into member values(1004, '강감찬', '부산광역시 금정구 부곡동', '010-1234-1004', '2024-03-22 16:40:00');
insert into member values(1005, '이순신', '광주광역시 광산구 우산동', '010-1234-1005', '2024-04-10 08:50:10');

insert into book values(10001, '태백산맥', '조정래', '문학수첩', 'Y', '2014-01-10 09:15:00');
insert into book values(10002, '데미안', '헤르만 헤세' ,'민음사', 'N' ,'2014-02-14 14:30:45');
insert into book values(10003, '토지' ,'박경리', '문학사상사','Y', '2014-03-01 11:05:20');
insert into book values(10004, '명품 자바 프로그래밍', '제임스 고슬링','한빛출판사', 'Y' ,'2014-03-22 16:40:00');
insert into book values(10005, '로미오와 줄리엣', '세익스피어', '열린책들', 'N', '2014-04-10 08:50:10');
insert into book values(10006, '삼국지', '나관중', '민음사', 'Y', '2014-04-05 09:12:02');
insert into book values(10007, '칼의 노래', '김훈', '문학동네' ,'Y' ,'2014-06-10 12:53:17');
insert into book values(10008, '데이터베이스', '래리 엘리슨', '한빛출판사','N', '2014-05-23 10:13:09');
insert into book values(10009, 'Linux 운영체제', '리누스 토발즈', '한빛출판사', 'Y' ,'2014-03-11 11:23:43');
insert into book values(10010, '어린 왕자', '생텍쥐베리', '열린책들', 'Y', '2014-05-13 15:27:21');

insert into loan (member_id, book_id, loan_date, return_date, actual_date)values(1001, 10002, '2024-03-01 10:02:31', '2024-03-15 10:02:31', '2024-03-13 09:44:19');
insert into loan (member_id, book_id, loan_date, return_date, actual_date)values(1002, 10004, '2024-03-05 15:10:02', '2024-03-19 15:10:02', '2024-03-12 17:12:30');
insert into loan (member_id, book_id, loan_date, return_date, actual_date)values(1003, 10008, '2024-04-01 11:01:12', '2024-04-15 11:01:12', NULL);
insert into loan (member_id, book_id, loan_date, return_date, actual_date)values(1002, 10001, '2024-04-10 14:32:01', '2024-04-24 14:32:01', '2024-04-22 13:56:32');
insert into loan (member_id, book_id, loan_date, return_date, actual_date)values(1005, 10004, '2024-04-15 16:24:21', '2024-04-29 16:24:21', NULL);
insert into loan (member_id, book_id, loan_date, return_date, actual_date)values(1004, 10006, '2024-05-01 09:12:09', '2024-05-15 09:12:09', '2024-05-14 09:21:27');
insert into loan (member_id, book_id, loan_date, return_date, actual_date)values(1001, 10007, '2024-05-03 13:51:07', '2024-05-17 13:51:07', '2024-05-16 14:05:10');
insert into loan (member_id, book_id, loan_date, return_date, actual_date)values(1003, 10009, '2024-06-01 11:15:43', '2024-06-15 11:15:43', NULL);
insert into loan (member_id, book_id, loan_date, return_date, actual_date)values(1004, 10004, '2024-06-02 12:30:52', '2024-06-16 12:30:52', NULL);
insert into loan (member_id, book_id, loan_date, return_date, actual_date)values(1002, 10008, '2024-06-05 10:06:17', '2024-06-19 10:06:17', NULL);

--4
select * from member;

--5
select title, author from book;

--6
select name, address
from member
where address like '부산%';

--7
select title
from book
where available = 'Y';

--8
select * from book
where book_id=10005;

--9
select member_id, name, hp
from member
where member_id=1002;

--10
select title from book
where reg_date like ('2014-03%');

--11
select title, author, publisher
from book
where publisher = '민음사';

--12
select loan_id, member_id, book_id
from loan
where actual_date is null;

--13
select * from member
where name like '김%';

--14
select name, address
from member
where address like '대구%' or address like '부산%';

--15
select book_id, title
from book
where book_id in (10003,10006);

--16
select title, author
from book
where author in ('조정래','박경리');

--17
select name, join_date
from member
where join_date < '2024-04-01';

--18
select loan_id, member_id, book_id, loan_date
from loan
where loan_date > '2024-05-01';

--19
select title, author, publisher
from book
where available = 'N';

--20
select *
from book
where title like '%자바%';

--21
select name, hp
from member
where hp <> ('010-1234-1003');

--22
select loan_id, member_id, book_id
from loan
where return_date < '2024-03-20';

--23
select * from member
order by name asc;

--24
select title, reg_date
from book
order by reg_date desc;

--25
select title 
from book
order by title asc
OFFSET 0 ROWS FETCH next 3 ROWS ONLY;

--26
select *
from member
order by join_date desc
offset 0 rows fetch next 1 rows only;

--27
select loan_id, loan_date
from loan
order by loan_date asc
offset 0 rows fetch next 2 rows only;

--28
select count(*)
from member;

--29
select count(*)
from book;

--30
select count(*)
from book
where available = 'Y';

--31
select publisher, count(book_id) as 출판_도서수
from book
group by publisher;

--32
select count(*)
from loan
where loan_date like '2024%';

--33
select member_id, count(book_id) as "대출_도서수"
from loan
group by member_id;

--34
select book_id, count(loan_date) as "대출_횟수"
from loan
group by book_id;

--35
select member_id, count(loan_id) as "회원_대출건수"
from loan
group by member_id
having count(loan_id) >=2;

--36
select book_id, count(loan_id) as "도서_대출건수"
from loan
group by book_id
having count(loan_id) >=2;

--37
select m.member_id, name, b.book_id, title, loan_date
from member m join loan l on m.member_id=l.member_id
join book b on l.book_id=b.book_id;

--38

SELECT name, count(loan_id) as 대출건수
from member m join loan l on m.member_id = l.member_id
group by name
having count(loan_id) >=3;

--39
select loan_id, name, title, loan_date
from loan l join member m on l.member_id=m.member_id
join book b on l.book_id = b.book_id
where loan_date < '2024-05-01';

--40
select title
from member m join loan l on m.member_id = l.member_id
join book b on b.book_id=l.book_id
where name = '김유신';

--41
select name
from member m join loan l on m.member_id = l.member_id
join book b on b.book_id=l.book_id
where title='태백산맥';

--42
select name, title
from member m join loan l on m.member_id = l.member_id
join book b on b.book_id=l.book_id
where name = '김춘추';

--43
select title, name
from member m join loan l on m.member_id = l.member_id
join book b on b.book_id=l.book_id
where loan_date like '2024-04%';

--44
select name, title
from member m join loan l on m.member_id = l.member_id
join book b on b.book_id=l.book_id
where actual_date is null;

--45
select name, title
from member m join loan l on m.member_id = l.member_id
join book b on b.book_id=l.book_id
where author = '조정래';

--46
select b.book_id, title
from book b left join loan l on b.book_id=l.book_id
where loan_id is null;

--47
select name, count(loan_id) as 총_건수
from member m join loan l on m.member_id = l.member_id
join book b on b.book_id=l.book_id
group by name
order by count(loan_id) desc;

--48
select name
from member
where member_id=(select member_id
                 from loan
                 group by member_id
                 having count(*) = (select max(cnt)
                                    from(
                                    select count(*) as cnt
                                    from loan
                                    group by member_id)));
                                    
--49
select title
from book
where book.publisher = (select book.publisher
               from book 
               where title = '데이터베이스') and title != '데이터베이스';
               
--50
select name
from member m join loan l on m.member_id = l.member_id
where l.book_id IN (select book_id
                   from loan
                   where book_id = 10004);

