/*
날짜 : 2025.07.18
이름 :서현우
내용 : sql연습문제 1
*/

--실습 1-1
alter session set "_oracle_script"=true;
create user shop identified by 1234;
grant connect, resource, unlimited tablespace to shop;

--실습 1-2
create table Customer(
    CID     varchar2(20)    PRIMARY key,
    name    varchar(20)     not null,
    hp      char(13)        default null unique,
    address  varchar(200)    default null,
    RDATE   DATE            not null
);
drop table customer;

create table Product(
    pno NUMBER(4) primary key,
    pname varchar(30) not null,
    stock NUMBER    default 0 not null ,
    price number    default null,
    company char(20) not null
);
drop table product;

create table Orders(
    ORD_NO number generated by default as identity primary key,
    ORD_CID varchar(20) not null,
    ORD_PNO NUMBER(4) not null,
    ORD_CNT number default 1 not null,
    ORD_DATE DATE NOT null
);
drop table orders;

--실습 1-3
insert into Customer values ('c101', '김유신', '010-1234-1001', '김해시 봉황동', '2022-01-01');
insert into Customer values ('c102', '김춘추', '010-1234-1002', '경주시 보문동', '2022-01-02');
insert into Customer values ('c103', '장보고', '010-1234-1003', '완도군 청산면', '2022-01-03');
insert into Customer values ('c104', '강감찬', '010-1234-1004', '서울시 마포구', '2022-01-04');
insert into Customer values ('c105', '이성계', null, null, '2022-01-05');
insert into Customer values ('c106', '정철', '010-1234-1006', '경기도 용인시', '2022-01-06');
insert into Customer values ('c107', '허준', null, null, '2022-01-07');
insert into Customer values ('c108', '이순신', '010-1234-1008', '서울시 영등포구', '2022-01-08');
insert into Customer values ('c109', '송상현', '010-1234-1009', '부산시 동래구', '2022-01-09');
insert into Customer values ('c110', '정약용', '010-1234-1010', '경기도 광주시', '2022-01-10');


insert into Product values (1, '새우깡', 5000, 1500, '농심');
insert into Product values (2, '초코파이', 2500, 2500, '오리온');
insert into Product values (3, '포카칩', 3600, 1700, '오리온');
insert into Product values (4, '양파링', 1250, 1800, '농심');
insert into Product values (5, '죠리퐁', 2200, NULL, '크라운');
insert into Product values (6, '마가렛트', 3500, 3500, '롯데');
insert into Product values (7, '뿌셔뿌셔', 1650, 1200, '오뚜기');



insert into Orders(ORD_CID, ORD_PNO, ORD_CNT, ORD_DATE) values ('c102', 3, 2, to_date('2022-07-01 13:15:10', 'YYYY-MM-DD HH24:MI:SS'));
insert into Orders(ORD_CID, ORD_PNO, ORD_CNT, ORD_DATE) values('c101', 4, 1, to_date('2022-07-01 14:16:11', 'YYYY-MM-DD HH24:MI:SS'));
insert into Orders(ORD_CID, ORD_PNO, ORD_CNT, ORD_DATE) values('c108',1,1,to_date('2022-07-01 17:23:18', 'YYYY-MM-DD HH24:MI:SS'));
insert into Orders(ORD_CID, ORD_PNO, ORD_CNT, ORD_DATE) values('c109',6,5,to_date('2022-07-02 10:46:36', 'YYYY-MM-DD HH24:MI:SS'));
insert into Orders(ORD_CID, ORD_PNO, ORD_CNT, ORD_DATE) values('c102',2,1,to_date('2022-07-03 09:15:37', 'YYYY-MM-DD HH24:MI:SS'));
insert into Orders(ORD_CID, ORD_PNO, ORD_CNT, ORD_DATE) values('c101',7,3,to_date('2022-07-03 12:35:12', 'YYYY-MM-DD HH24:MI:SS'));
insert into Orders(ORD_CID, ORD_PNO, ORD_CNT, ORD_DATE) values('c110',1,2,to_date('2022-07-03 16:55:36', 'YYYY-MM-DD HH24:MI:SS'));
insert into Orders(ORD_CID, ORD_PNO, ORD_CNT, ORD_DATE) values('c104',2,4,to_date('2022-07-04 14:23:23', 'YYYY-MM-DD HH24:MI:SS'));
insert into Orders(ORD_CID, ORD_PNO, ORD_CNT, ORD_DATE) values('c102',1,3,to_date('2022-07-04 21:54:34', 'YYYY-MM-DD HH24:MI:SS'));
insert into Orders(ORD_CID, ORD_PNO, ORD_CNT, ORD_DATE) values('c107',6,1,to_date('2022-07-05 14:21:03', 'YYYY-MM-DD HH24:MI:SS'));

--실습 1-4
select * from customer;

--실습 1-5
select cid, name, hp from customer;

--실습 1-6
select * from product;

--실습 1-7
select company from product;

--실습 1-8
select distinct company from product;

--실습 1-9
select pname, price from product;

--실습 1-10
select pname, price+500 "조정단가" from product;

--실습 1-11
select pname, stock, price
from product
where company = '오리온';

--실습 1-12
select ord_pno, ord_cnt, ord_date
from orders
where ord_cid = 'c102';

--실습 1-13
select ord_pno, ord_cnt, ord_date 
from orders 
where ord_cid='c102' and ord_cnt>=2;

--실습 1-14
select * from product
where price >= 1000 and price <= 2000;

--실습 1-15
select cid, name, hp, address 
from customer
where name like '김%';

--실습 1-16
select cid, name, hp, address from customer
where name like '__';

--실습 1-17
select * from customer 
where hp is null;

--실습 1-18
select * from customer
where address is not null;

--실습 1-19
select * from customer 
order by rdate desc;

--실습 1-20
select * from orders
where ord_cnt >=3
order by ord_cnt desc, ord_pno asc;

--실습 1-21
select avg(price) from product;

--실습 1-22
select sum(stock) as "재고량 합계"
from product
where company='농심';

--실습 1-23
select count(cid) as 고객수
from customer;

--실습 1-24
select count(distinct company) as "제조업체 수" 
from product;

--실습 1-25
select ord_pno as "주문 상품번호", sum(ord_cnt) as "총 주문수량" 
from orders
group by ord_pno
order by ord_pno;


--실습 1-26
select company as 제조업체, count(*) as 제품수, max(price) as 최고가 
from product
group by company
order by company;

--실습 1-27
select company as 제조업체, count(*) as 제품수, max(price) as 최고가
from product
group by company 
having count(*) >=2;

--실습 1-28
select ord_pno, ord_cid, sum(ord_cnt) as "총 주문수량"
from orders
group by ord_pno, ord_cid
order by ord_pno;

--실습 1-29
select distinct ord_cid, pname 
from orders a join product b on a.ord_pno=b.pno
where ord_cid = 'c102';

--위와동일
select distinct ord_cid, pname 
from orders a, product b
where a.ord_pno=b.pno and ord_cid = 'c102';



--실습 1-30
select ord_cid, name, pname, ord_date
from orders a join customer b 
on a.ord_cid = b.cid
join product c on a.ord_pno = c.pno
where ord_date like '2022-07-03%';
